import { DataCatalogEntity, CdcPipelineStatus, OlapCube, DataLineageNode, ScdRecord } from './types';

export const ENTERPRISE_DATA_CATALOG: DataCatalogEntity[] = [
  {
    id: 'FACT_ORDERS_POS',
    name: 'fact_pos_transactions',
    nameAr: 'جدول حقائق مبيعات نقاط البيع (Fact)',
    type: 'FACT',
    schemaModel: 'STAR_SCHEMA',
    storageTier: 'HOT_MEMORY',
    rowCount: '48,920,400',
    storageSizeMb: 14200,
    lastUpdated: 'Live Streaming (0s ago)',
    descriptionEn: 'Granular sales transaction lines with item, tender, tax, discounts, and timestamp keys.',
    descriptionAr: 'بيانات تفاصيل الفواتير والعمليات البيعية مع مفاتيح الضرائب والخصومات والعملاء.',
    columns: [
      { name: 'order_sk', type: 'BIGINT', isPrimary: true, description: 'Surrogate primary key' },
      { name: 'date_dim_id', type: 'INT', isForeign: true, description: 'FK to dim_date' },
      { name: 'branch_dim_id', type: 'INT', isForeign: true, description: 'FK to dim_branch' },
      { name: 'menu_item_dim_id', type: 'INT', isForeign: true, description: 'FK to dim_menu_item' },
      { name: 'customer_dim_id', type: 'INT', isForeign: true, description: 'FK to dim_customer' },
      { name: 'quantity', type: 'NUMERIC(10,2)', description: 'Order line quantity' },
      { name: 'net_amount_sar', type: 'NUMERIC(14,2)', description: 'Net line total in SAR' },
      { name: 'vat_amount_sar', type: 'NUMERIC(14,2)', description: 'ZATCA VAT 15%' },
      { name: 'cogs_amount_sar', type: 'NUMERIC(14,2)', description: 'Calculated recipe COGS' },
    ],
  },
  {
    id: 'DIM_BRANCH_SCD2',
    name: 'dim_branch_scd2',
    nameAr: 'بُعد الفروع مع التتبع التاريخي (SCD Type 2)',
    type: 'DIMENSION',
    schemaModel: 'STAR_SCHEMA',
    storageTier: 'WARM_LAKEHOUSE',
    rowCount: '1,240',
    storageSizeMb: 8.4,
    lastUpdated: '10 mins ago',
    scdType: 'TYPE_2',
    descriptionEn: 'Tracks geographical changes, seating capacity, regional assignments, and franchise status over time.',
    descriptionAr: 'يحتفظ بالتاريخ الزمني لأي تعديل في الموقع الجغرافي أو السعة الاستيعابية أو العقود.',
    columns: [
      { name: 'branch_sk', type: 'INT', isPrimary: true, description: 'Surrogate branch key' },
      { name: 'branch_code', type: 'VARCHAR(32)', description: 'Natural business key' },
      { name: 'region_name', type: 'VARCHAR(64)', description: 'Central / Western / Eastern' },
      { name: 'franchise_entity', type: 'VARCHAR(128)', description: 'Owner legal entity' },
      { name: 'valid_from', type: 'TIMESTAMP', description: 'Effective start date' },
      { name: 'valid_to', type: 'TIMESTAMP', description: 'Effective end date (NULL if current)' },
      { name: 'is_current', type: 'BOOLEAN', description: 'True if active version' },
    ],
  },
  {
    id: 'DIM_MENU_SNOWFLAKE',
    name: 'dim_menu_item_hierarchy',
    nameAr: 'بُعد الأصناف الهرمي المتفرع (Snowflake Schema)',
    type: 'DIMENSION',
    schemaModel: 'SNOWFLAKE_SCHEMA',
    storageTier: 'HOT_MEMORY',
    rowCount: '18,500',
    storageSizeMb: 42.1,
    lastUpdated: '1 hour ago',
    scdType: 'TYPE_2',
    descriptionEn: 'Normalized hierarchy: Item -> Subcategory -> Department -> Recipe BOM -> Allergen Registry.',
    descriptionAr: 'تفريغ هرمي للوصفات وقوائم الطعام والمجموعات والمطبخ المركزي.',
    columns: [
      { name: 'item_sk', type: 'INT', isPrimary: true, description: 'Surrogate item key' },
      { name: 'item_sku', type: 'VARCHAR(64)', description: 'SKU Barcode' },
      { name: 'recipe_bom_id', type: 'INT', isForeign: true, description: 'FK to recipe BOM' },
      { name: 'current_unit_cost_sar', type: 'NUMERIC(10,2)', description: 'Real-time BOM cost' },
      { name: 'is_halal_certified', type: 'BOOLEAN', description: 'Halal regulatory flag' },
    ],
  },
  {
    id: 'MV_DAILY_BRANCH_METRICS',
    name: 'mv_daily_store_financials',
    nameAr: 'عرض مجدول تراكمي للأداء المالي اليومي (Materialized View)',
    type: 'MATERIALIZED_VIEW',
    schemaModel: 'STAR_SCHEMA',
    storageTier: 'HOT_MEMORY',
    rowCount: '450,000',
    storageSizeMb: 180,
    lastUpdated: 'Incrementally Refreshed (15s ago)',
    descriptionEn: 'Pre-computed daily rollups for GMV, VAT, Food Cost %, Labor %, and Net EBITDA.',
    descriptionAr: 'حسابات مسبقة التجميع لسرعة استجابة لوحات القيادة في أجزاء من الثانية.',
    columns: [
      { name: 'rollup_date', type: 'DATE', isPrimary: true, description: 'Date key' },
      { name: 'branch_id', type: 'INT', isPrimary: true, description: 'Branch key' },
      { name: 'total_gmv_sar', type: 'NUMERIC(16,2)', description: 'Aggregated gross sales' },
      { name: 'total_orders', type: 'INT', description: 'Total tickets' },
      { name: 'avg_basket_sar', type: 'NUMERIC(10,2)', description: 'Calculated AOV' },
    ],
  },
];

export const CDC_PIPELINES: CdcPipelineStatus[] = [
  {
    id: 'CDC-01',
    sourceTable: 'public.pos_orders (PostgreSQL 16)',
    targetLake: 'lakehouse.raw_pos_events (Iceberg / Parquet)',
    status: 'STREAMING',
    lagMs: 12,
    recordsPerSec: 2840,
    totalEventsProcessed: '148,290,120',
    connectorType: 'DEBEZIUM_POSTGRES',
  },
  {
    id: 'CDC-02',
    sourceTable: 'public.inventory_ledger (PostgreSQL 16)',
    targetLake: 'lakehouse.inventory_movements',
    status: 'STREAMING',
    lagMs: 18,
    recordsPerSec: 920,
    totalEventsProcessed: '38,410,500',
    connectorType: 'DEBEZIUM_POSTGRES',
  },
  {
    id: 'CDC-03',
    sourceTable: 'public.zatca_signed_invoices (WORM Storage)',
    targetLake: 'lakehouse.compliance_zatca_lake',
    status: 'SYNCED',
    lagMs: 5,
    recordsPerSec: 1450,
    totalEventsProcessed: '52,190,000',
    connectorType: 'KAFKA_AVRO',
  },
];

export const OLAP_CUBES: OlapCube[] = [
  {
    id: 'CUBE_REVENUE_TIME',
    cubeNameEn: 'Global Multidimensional Revenue & Margin Cube',
    cubeNameAr: 'مكعب التحليل متعدد الأبعاد للإيرادات والهوامش',
    dimensions: ['Time (Year/Quarter/Month/Day/Hour)', 'Geography (Region/City/Branch)', 'Channel', 'Menu Category'],
    measures: ['GMV', 'Net Sales', 'COGS', 'EBITDA', 'Discounts', 'VAT 15%', 'Ticket Count'],
    aggregationCadence: '1_MIN',
    cacheHitRatio: 99.4,
    queryLatencyP99Ms: 8.2,
  },
  {
    id: 'CUBE_SUPPLY_INVENTORY',
    cubeNameEn: 'Supply Chain, Recipe BOM & Shrinkage Cube',
    cubeNameAr: 'مكعب تحليل سلاسل الإمداد ومطابقة الوصفات والهدر',
    dimensions: ['Supplier', 'Warehouse', 'Ingredient Master', 'Batch Expiry Lot', 'Branch'],
    measures: ['Theoretical Usage', 'Actual Count Variance', 'Spoilage Value', 'Yield %', 'Lead Time'],
    aggregationCadence: '1_HOUR',
    cacheHitRatio: 98.7,
    queryLatencyP99Ms: 14.5,
  },
];

export const DATA_LINEAGE_NODES: DataLineageNode[] = [
  { id: 'SRC_POS', label: 'POS Terminal Ingress', category: 'SOURCE_OLTP', status: 'HEALTHY' },
  { id: 'CDC_KAFKA', label: 'Kafka Debezium Stream', category: 'CDC_STREAM', status: 'SYNCED' },
  { id: 'BRONZE_PARQUET', label: 'Bronze Raw Parquet Lake', category: 'BRONZE_LAKE', status: 'HEALTHY' },
  { id: 'SILVER_DW', label: 'Silver Star Schema Warehouse', category: 'SILVER_WAREHOUSE', status: 'SYNCED' },
  { id: 'GOLD_CUBES', label: 'Gold Aggregated OLAP Cubes', category: 'GOLD_MART', status: 'HEALTHY' },
  { id: 'BI_POWER', label: 'Executive BI & ML Engines', category: 'BI_DASHBOARD', status: 'HEALTHY' },
];

export const SCD_SAMPLE_LOG: ScdRecord[] = [
  {
    surrogateKey: 'BR-SK-10492',
    businessKey: 'BRANCH_RUH_OLAYA_01',
    entityName: 'Branch Registry',
    attributeChanged: 'Seating Capacity & Floor Tables',
    oldValue: '120 Seats / 28 Tables',
    newValue: '180 Seats / 42 Tables (Expansion)',
    validFrom: '2026-08-01 00:00:00',
    validTo: null,
    isCurrent: true,
  },
  {
    surrogateKey: 'BR-SK-09120',
    businessKey: 'BRANCH_RUH_OLAYA_01',
    entityName: 'Branch Registry',
    attributeChanged: 'Seating Capacity & Floor Tables',
    oldValue: '90 Seats / 20 Tables',
    newValue: '120 Seats / 28 Tables',
    validFrom: '2025-01-01 00:00:00',
    validTo: '2026-07-31 23:59:59',
    isCurrent: false,
  },
];
