// ============================================================================
// ENTERPRISE SEMANTIC SEARCH ENGINE (CROSS-DOC, CITATIONS, KNOWLEDGE)
// SPRINT 3.3
// ============================================================================

import { SemanticSearchResult } from '../types';

export class EnterpriseSearchEngine {
  private knowledgeCorpus: SemanticSearchResult[] = [];

  constructor() {
    this.initCorpus();
  }

  private initCorpus(): void {
    this.knowledgeCorpus = [
      {
        documentId: 'doc-sop-meat-prep-01',
        documentTitle: 'SOP-202: Premium Wagyu Beef Thawing, Aging & Sear Protocol',
        documentSource: 'KITCHEN_SOP',
        matchScorePct: 99.4,
        matchedSnippet: 'Wagyu loins must undergo dry-aging at 1.5°C with 75% relative humidity for a minimum of 21 days. Internal cook temperature for Medium-Rare must hit precisely 54°C before a 5-minute warm resting cycle.',
        matchedSnippetAr: 'يجب أن تخضع قطع الواغيو للتعميق الجاف عند 1.5 درجة مئوية ورطوبة 75% لمدة لا تقل عن 21 يوماً. درجة حرارة الطهي الداخلية للميديم-رير يجب أن تصل بدقة إلى 54 مئوية قبل مرحلة الإراحة لمدة 5 دقائق.',
        citations: [
          { pageNumber: 4, sectionTitle: 'Section 3.2: Thermal Sear & Rest Times', exactQuote: 'Rest duration is mandatory to prevent myoglobin loss.' },
          { pageNumber: 7, sectionTitle: 'Section 4.1: SFDA Meat Storage Compliance', exactQuote: 'Daily calibrated probe records must be archived in digital HACCP log.' },
        ],
        verifiedFactual: true,
      },
      {
        documentId: 'doc-zatca-phase2-rules-02',
        documentTitle: 'ZATCA Phase 2 E-Invoicing Technical & Cryptographic Guidelines (Saudi Arabia)',
        documentSource: 'ZATCA_REGULATIONS',
        matchScorePct: 98.8,
        matchedSnippet: 'Simplified B2C tax invoices require an embedded Base64-encoded TLV QR code containing Seller Name, VAT Number, Timestamp, Total with VAT, VAT Total, ECDSA P-256 SHA-256 Hash, and ZATCA Public Key signature.',
        matchedSnippetAr: 'تتطلب الفواتير الضريبية المبسطة B2C رمز QR مشفر بتنسيق TLV يحتوي على اسم البائع، الرقم الضريبي، الطابع الزمني، الإجمالي شامل الضريبة، إجمالي الضريبة، وتوقيع ECDSA P-256.',
        citations: [
          { pageNumber: 12, sectionTitle: 'Article 5: Cryptographic Stamp Specification', exactQuote: 'TLV Tag 6 holds the ECDSA signature generated by certified EGS device.' },
          { pageNumber: 18, sectionTitle: 'Article 9: Clearance vs Reporting Timelines', exactQuote: 'B2C invoices must be reported to Fatoora portal within 24 hours of issuance.' },
        ],
        verifiedFactual: true,
      },
      {
        documentId: 'doc-recipe-truffle-burger-03',
        documentTitle: 'RECIPE-104: Artisan Black Truffle & Smoked Bone Marrow Burger',
        documentSource: 'RECIPE_BOOK',
        matchScorePct: 97.5,
        matchedSnippet: 'Patty composition: 70% A5 Wagyu Chuck, 30% Smoked Bone Marrow. Season with 1.8% kosher salt and freshly cracked black pepper. Top with 15g shaved Italian black summer truffles and melted Gruyère.',
        matchedSnippetAr: 'تركيبة اللحم: 70% واغيو A5 و30% نخاع عظم مدخن. التتبيل بـ 1.8% ملح كوشير وفلفل أسود مجروش. التزيين بـ 15 جم كمأة سوداء إيطالية وجبن غرويير ذائب.',
        citations: [
          { pageNumber: 2, sectionTitle: 'Ingredients & Yield Breakdown', exactQuote: 'Yield per batch: 40 patties of 180g each.' },
        ],
        verifiedFactual: true,
      },
      {
        documentId: 'doc-hr-saudi-labor-04',
        documentTitle: 'HR-POL-08: Saudi Labor Law Overtime & Rest Day Regulations',
        documentSource: 'HR_MANUAL',
        matchScorePct: 96.0,
        matchedSnippet: 'Standard working hours are capped at 8 hours per day or 48 hours per week. Overtime hours are compensated at normal hourly wage plus 50% premium pursuant to Article 107 of Saudi Labor Law.',
        matchedSnippetAr: 'ساعات العمل الرسمية بحد أقصى 8 ساعات يومياً أو 48 ساعة أسبوعياً. يتم احتساب ساعات العمل الإضافي بالأجر العادي مضافاً إليه 50% وفق المادة 107 من نظام العمل السعودي.',
        citations: [
          { pageNumber: 15, sectionTitle: 'Article 107: Overtime Calculation', exactQuote: 'All hours during official Eid holidays are calculated as overtime.' },
        ],
        verifiedFactual: true,
      },
    ];
  }

  public search(query: string): SemanticSearchResult[] {
    const q = query.toLowerCase().trim();
    if (!q) return this.knowledgeCorpus;

    return this.knowledgeCorpus.filter((item) => {
      return (
        item.documentTitle.toLowerCase().includes(q) ||
        item.matchedSnippet.toLowerCase().includes(q) ||
        (item.matchedSnippetAr && item.matchedSnippetAr.includes(q)) ||
        item.documentSource.toLowerCase().includes(q)
      );
    });
  }
}

export const enterpriseSearchEngine = new EnterpriseSearchEngine();
