import { MarketplacePlugin, WebhookEndpoint, ApiMarketplaceDoc } from './types';

export const ENTERPRISE_MARKETPLACE_PLUGINS: MarketplacePlugin[] = [
  {
    id: 'PLG-DEL-JAHEZ',
    nameEn: 'Jahez Global Delivery Hub',
    nameAr: 'ربط منصة جاهز للتوصيل السريع',
    category: 'DELIVERY_AGGREGATOR',
    vendor: 'Jahez International Co.',
    iconName: 'Bike',
    version: 'v3.4.1',
    rating: 4.9,
    installCount: 1420,
    priceMonthlySar: 0,
    isInstalled: true,
    status: 'CERTIFIED',
    descriptionEn: 'Full two-way menu sync, automated order injection directly into KDS, and live courier tracking.',
    descriptionAr: 'مزامنة كاملة لقائمة الطعام وإرسال الطلبات مباشرة لشاشات المطبخ وتتبع المناديب.',
    webhookEvents: ['jahez.order.created', 'jahez.order.dispatched', 'jahez.order.delivered'],
    oauthScopes: ['orders.read', 'orders.write', 'menu.sync'],
    documentationUrl: 'https://developer.enterprise-pos.com/plugins/jahez',
  },
  {
    id: 'PLG-DEL-HUNGER',
    nameEn: 'HungerStation Direct Dispatch',
    nameAr: 'ربط منصة هنقرستيشن المباشر',
    category: 'DELIVERY_AGGREGATOR',
    vendor: 'HungerStation LLC',
    iconName: 'ShoppingBag',
    version: 'v3.2.0',
    rating: 4.8,
    installCount: 1390,
    priceMonthlySar: 0,
    isInstalled: true,
    status: 'CERTIFIED',
    descriptionEn: 'Instant kitchen injection, automated item 86 out-of-stock sync, and consolidated statement audit.',
    descriptionAr: 'حقن فوري في المطبخ، إيقاف الأصناف التلقائي، ومطابقة الفواتير المالية.',
    webhookEvents: ['hunger.order.created', 'hunger.rider.arrived'],
    oauthScopes: ['orders.write', 'inventory.sync'],
    documentationUrl: 'https://developer.enterprise-pos.com/plugins/hungerstation',
  },
  {
    id: 'PLG-ERP-ORACLE',
    nameEn: 'Oracle NetSuite Enterprise ERP Sync',
    nameAr: 'مزامنة أوراكل نت سويت المحاسبية',
    category: 'ACCOUNTING_ERP',
    vendor: 'Oracle Cloud ERP',
    iconName: 'Database',
    version: 'v4.1.0',
    rating: 4.95,
    installCount: 380,
    priceMonthlySar: 450,
    isInstalled: true,
    status: 'CERTIFIED',
    descriptionEn: 'Real-time journal entry posting, inventory GL ledger synchronization, and automated 3-way matching.',
    descriptionAr: 'ترحيل قيود اليومية آلياً ومزامنة شجرة الحسابات والمطابقة الثلاثية للمشتريات.',
    webhookEvents: ['journal.posted', 'inventory.adjusted', 'po.matched'],
    oauthScopes: ['finance.full_access', 'gl.ledger_write'],
    documentationUrl: 'https://developer.enterprise-pos.com/plugins/netsuite',
  },
  {
    id: 'PLG-PAY-MADA',
    nameEn: 'Mada Direct Terminal & Apple Pay Ingress',
    nameAr: 'بوابة مدى والمدفوعات الإلكترونية المباشرة',
    category: 'PAYMENT_GATEWAY',
    vendor: 'Saudi Payments Network (Mada)',
    iconName: 'CreditCard',
    version: 'v5.0.0',
    rating: 5.0,
    installCount: 2400,
    priceMonthlySar: 0,
    isInstalled: true,
    status: 'CERTIFIED',
    descriptionEn: 'National payment gateway driver supporting EMV chip, NFC contactless, and instant settlement.',
    descriptionAr: 'المشغل الوطني للمدفوعات عبر الرقاقة الذكية والاتصال اللاتلامسي والتسوية الفورية.',
    webhookEvents: ['payment.authorized', 'payment.settled', 'payment.refunded'],
    oauthScopes: ['payments.process', 'settlement.read'],
    documentationUrl: 'https://developer.enterprise-pos.com/plugins/mada',
  },
  {
    id: 'PLG-CRM-WHATSAPP',
    nameEn: 'Meta WhatsApp Business Cloud API',
    nameAr: 'بوابة واتساب للأعمال الرسمية من ميتا',
    category: 'MARKETING_CRM',
    vendor: 'Meta Platforms Inc.',
    iconName: 'MessageSquare',
    version: 'v2.8.0',
    rating: 4.9,
    installCount: 1120,
    priceMonthlySar: 120,
    isInstalled: true,
    status: 'CERTIFIED',
    descriptionEn: 'Verified green badge messaging for e-receipts, reservation confirmations, and VIP marketing journeys.',
    descriptionAr: 'إرسال الفواتير الإلكترونية المعتمدة وتأكيد الحجوزات وحملات الولاء التلقائية.',
    webhookEvents: ['whatsapp.message.delivered', 'whatsapp.message.read', 'whatsapp.button.clicked'],
    oauthScopes: ['messages.send', 'templates.manage'],
    documentationUrl: 'https://developer.enterprise-pos.com/plugins/meta-whatsapp',
  },
];

export const ENTERPRISE_WEBHOOK_ENDPOINTS: WebhookEndpoint[] = [
  {
    id: 'WH-01',
    name: 'Production Financial ERP Ledger Listener',
    targetUrl: 'https://erp.enterprise-pos.com/api/v2/webhooks/pos-journal',
    eventsSubscribed: ['order.paid', 'shift.closed', 'vat.calculated'],
    secretKey: 'whsec_enterprise_prod_984920491823',
    status: 'HEALTHY',
    successRatePercent: 99.98,
    lastDeliveredAt: '2026-08-27 13:44:12',
  },
  {
    id: 'WH-02',
    name: 'Real-Time Food Safety & IoT Thermal Logger',
    targetUrl: 'https://iot.enterprise-pos.com/ingest/sensors',
    eventsSubscribed: ['sensor.temp_alert', 'fridge.door_open'],
    secretKey: 'whsec_iot_sensors_102938491029',
    status: 'HEALTHY',
    successRatePercent: 100.0,
    lastDeliveredAt: '2026-08-27 13:45:00',
  },
];

export const ENTERPRISE_API_DOCS: ApiMarketplaceDoc[] = [
  {
    id: 'API-01',
    endpoint: '/api/v1/orders/create',
    method: 'POST',
    summaryEn: 'Submit order payload with table, modifiers, payment tender & ZATCA metadata.',
    summaryAr: 'إنشاء طلب جديد مع تحديد الطاولة والتعديلات والوسيلة البيعية ومعلومات زاتكا.',
    rateLimitPerMin: 10000,
    requiredScope: 'orders:write',
  },
  {
    id: 'API-02',
    endpoint: '/api/v1/analytics/realtime-kpi',
    method: 'GET',
    summaryEn: 'Stream live GMV, EBITDA, Kitchen SLA, and Prime Cost metrics for active tenant.',
    summaryAr: 'بث مؤشرات الأداء الحية والمبيعات وهوامش الأرباح وسرعة المطبخ.',
    rateLimitPerMin: 5000,
    requiredScope: 'analytics:read',
  },
  {
    id: 'API-03',
    endpoint: '/api/v1/hrms/payroll/wps-export',
    method: 'GET',
    summaryEn: 'Generate Saudi Wage Protection System (WPS) compliant text file for commercial banks.',
    summaryAr: 'توليد ملف حماية الأجور المعتمد لنظام سداد ووزارة الموارد البشرية.',
    rateLimitPerMin: 600,
    requiredScope: 'hrms:admin',
  },
];
