import {
  CostCenter,
  FixedAsset,
  BankReconciliationItem,
  JournalEntry,
  FinancialStatementItem,
} from './types';

export const ENTERPRISE_COST_PROFIT_CENTERS: CostCenter[] = [
  {
    id: 'CC-01',
    code: 'CC-RUH-KITCHEN',
    nameEn: 'Central Commissary Kitchen - Riyadh',
    nameAr: 'المطبخ المركزي المركزي - الرياض',
    type: 'COST_CENTER',
    budgetAnnualSar: 4200000,
    spentYtdSar: 2650000,
    varianceSar: 150000,
    variancePercent: 5.4,
    manager: 'Chef Tariq Al-Mansoor',
  },
  {
    id: 'CC-02',
    code: 'CC-FLEET-LOGISTICS',
    nameEn: 'Cold-Chain Delivery & Fleet Operations',
    nameAr: 'أسطول النقل المبرد والخدمات اللوجستية',
    type: 'COST_CENTER',
    budgetAnnualSar: 1800000,
    spentYtdSar: 1120000,
    varianceSar: -40000,
    variancePercent: -3.4,
    manager: 'Eng. Fares Al-Otaibi',
  },
  {
    id: 'PC-01',
    code: 'PC-BR-OLAYA',
    nameEn: 'Olaya Flagship Dine-In & Drive-Thru',
    nameAr: 'فرع العليا الرئيسي - صالة وطلبات سيارات',
    type: 'PROFIT_CENTER',
    budgetAnnualSar: 6500000,
    spentYtdSar: 7890000,
    varianceSar: 1390000,
    variancePercent: 21.4,
    manager: 'Sultan Al-Harbi',
  },
  {
    id: 'PC-02',
    code: 'PC-BR-REDSEA',
    nameEn: 'Red Sea Mall Fine-Casual Store',
    nameAr: 'فرع رد سي مول - جدة',
    type: 'PROFIT_CENTER',
    budgetAnnualSar: 5200000,
    spentYtdSar: 6140000,
    varianceSar: 940000,
    variancePercent: 18.1,
    manager: 'Mariam Al-Ghamdi',
  },
];

export const FIXED_ASSETS_REGISTER: FixedAsset[] = [
  {
    id: 'FA-01',
    assetTag: 'AST-KTC-RATIONAL-01',
    nameEn: 'Rational iCombi Pro 20-Grid Combi Oven',
    nameAr: 'فرن كومبي ذكي راشونال 20 صينية',
    category: 'KITCHEN_EQUIPMENT',
    purchaseDate: '2024-01-15',
    purchaseCostSar: 145000,
    salvageValueSar: 15000,
    usefulLifeMonths: 84,
    depreciationMethod: 'STRAIGHT_LINE',
    accumulatedDepreciationSar: 46428,
    netBookValueSar: 98572,
    location: 'Riyadh Central Commissary',
  },
  {
    id: 'FA-02',
    assetTag: 'AST-POS-SUNMI-40',
    nameEn: 'Enterprise Dual-Screen POS Terminals (Batch of 40)',
    nameAr: 'محطات كاشير شاشة مزدوجة (دفعة 40 جهاز)',
    category: 'POS_HARDWARE',
    purchaseDate: '2025-03-01',
    purchaseCostSar: 92000,
    salvageValueSar: 4000,
    usefulLifeMonths: 48,
    depreciationMethod: 'STRAIGHT_LINE',
    accumulatedDepreciationSar: 31166,
    netBookValueSar: 60834,
    location: 'All Branches (Network-Wide)',
  },
  {
    id: 'FA-03',
    assetTag: 'AST-FLT-ISUZU-03',
    nameEn: 'Isuzu ThermoKing Refrigerated Delivery Van 4.5T',
    nameAr: 'شاحنة إيسوزو مبردة للنقل الغذائي 4.5 طن',
    category: 'VEHICLES',
    purchaseDate: '2024-06-10',
    purchaseCostSar: 185000,
    salvageValueSar: 25000,
    usefulLifeMonths: 60,
    depreciationMethod: 'STRAIGHT_LINE',
    accumulatedDepreciationSar: 69333,
    netBookValueSar: 115667,
    location: 'Central Logistics Depot',
  },
];

export const BANK_RECONCILIATIONS: BankReconciliationItem[] = [
  {
    id: 'REC-01',
    statementDate: '2026-08-27',
    bankAccount: 'Al Rajhi Bank (SAR Operating Acc - ...4901)',
    glAccountCode: '1010-01',
    bankStatementBalanceSar: 8452190.5,
    bookBalanceSar: 8452190.5,
    unreconciledDifferenceSar: 0,
    matchedTransactionsCount: 4210,
    unmatchedTransactionsCount: 0,
    status: 'RECONCILED',
  },
  {
    id: 'REC-02',
    statementDate: '2026-08-27',
    bankAccount: 'Saudi National Bank - SNB (Mada POS Settlement - ...8120)',
    glAccountCode: '1010-02',
    bankStatementBalanceSar: 3894210.0,
    bookBalanceSar: 3894210.0,
    unreconciledDifferenceSar: 0,
    matchedTransactionsCount: 18940,
    unmatchedTransactionsCount: 0,
    status: 'RECONCILED',
  },
];

export const GENERAL_LEDGER_JOURNALS: JournalEntry[] = [
  {
    id: 'JV-2026-08-019',
    journalNumber: 'JV-2026-08-019',
    postingDate: '2026-08-27',
    descriptionEn: 'Daily Consolidated POS Revenue, VAT 15% & Mada Settlement Clearance',
    descriptionAr: 'قيد المبيعات اليومية المجمعة وضريبة القيمة المضافة 15% وتسوية مدى',
    reference: 'POS-EGS-SYNC-20260827',
    totalDebitSar: 425890.0,
    totalCreditSar: 425890.0,
    status: 'POSTED',
    preparedBy: 'Automated Accounting Engine (ZATCA Sync)',
    approvedBy: 'Hassan Al-Amoudi (CFO)',
    lines: [
      {
        accountCode: '1010-02',
        accountName: 'SNB Mada Settlement Clearing',
        debitSar: 370339.13,
        creditSar: 0,
        notes: 'Mada & Visa Settlement Net',
      },
      {
        accountCode: '1010-00',
        accountName: 'Store Cash on Hand Vault',
        debitSar: 55550.87,
        creditSar: 0,
        notes: 'Cash collected in cashiers till',
      },
      {
        accountCode: '4010-00',
        accountName: 'Food & Beverage Revenue (Net of Discounts)',
        debitSar: 0,
        creditSar: 370339.13,
        notes: 'Tax-exclusive sales',
      },
      {
        accountCode: '2150-00',
        accountName: 'ZATCA Output VAT 15% Payable',
        debitSar: 0,
        creditSar: 55550.87,
        notes: 'ZATCA Phase 2 E-Invoice standard 15% VAT',
      },
    ],
  },
];

export const BALANCE_SHEET_DATA: FinancialStatementItem[] = [
  { accountCode: '1000', accountNameEn: 'Cash & Cash Equivalents', accountNameAr: 'النقد وما في حكمه', currentPeriodSar: 12346400, priorPeriodSar: 10890000, varianceSar: 1456400, variancePercent: 13.4 },
  { accountCode: '1100', accountNameEn: 'Accounts Receivable (Trade & Delivery)', accountNameAr: 'الذمم المدينة وحسابات تطبيقات التوصيل', currentPeriodSar: 2840000, priorPeriodSar: 2450000, varianceSar: 390000, variancePercent: 15.9 },
  { accountCode: '1200', accountNameEn: 'Inventories (Raw Materials & Finished)', accountNameAr: 'المخزون السلعي (المواد الخام والجاهزة)', currentPeriodSar: 3450000, priorPeriodSar: 3580000, varianceSar: -130000, variancePercent: -3.6 },
  { accountCode: '1500', accountNameEn: 'Property, Plant & Kitchen Equipment (Net)', accountNameAr: 'الأصول الثابتة والمعدات والمطابخ (بالصافي)', currentPeriodSar: 18450000, priorPeriodSar: 19100000, varianceSar: -650000, variancePercent: -3.4 },
  { accountCode: '2000', accountNameEn: 'Accounts Payable (Vendors & Suppliers)', accountNameAr: 'الذمم الدائنة والموردين', currentPeriodSar: 4120000, priorPeriodSar: 3980000, varianceSar: 140000, variancePercent: 3.5 },
  { accountCode: '2150', accountNameEn: 'ZATCA VAT & Withholding Tax Payable', accountNameAr: 'ضريبة القيمة المضافة المستحقة (زاتكا)', currentPeriodSar: 1850000, priorPeriodSar: 1620000, varianceSar: 230000, variancePercent: 14.2 },
  { accountCode: '3000', accountNameEn: 'Shareholders Equity & Retained Earnings', accountNameAr: 'حقوق الملكية والأرباح المبقاة', currentPeriodSar: 31116400, priorPeriodSar: 30420000, varianceSar: 696400, variancePercent: 2.3 },
];

export const PROFIT_AND_LOSS_DATA: FinancialStatementItem[] = [
  { accountCode: '4000', accountNameEn: 'Gross Revenue (GMV)', accountNameAr: 'إجمالي الإيرادات (GMV)', currentPeriodSar: 14258900, priorPeriodSar: 12410000, varianceSar: 1848900, variancePercent: 14.9 },
  { accountCode: '4100', accountNameEn: 'Discounts, Promos & Loyalty Redemptions', accountNameAr: 'الخصومات والعروض الترويجية والولاء', currentPeriodSar: -1860450, priorPeriodSar: -1380000, varianceSar: -480450, variancePercent: 34.8 },
  { accountCode: '4500', accountNameEn: 'Net Sales Revenue', accountNameAr: 'صافي المبيعات', currentPeriodSar: 12398450, priorPeriodSar: 11030000, varianceSar: 1368450, variancePercent: 12.4 },
  { accountCode: '5000', accountNameEn: 'Cost of Goods Sold (COGS - Ingredients)', accountNameAr: 'تكلفة البضاعة المباعة (المكونات والمواد)', currentPeriodSar: -3545958, priorPeriodSar: -3419300, varianceSar: -126658, variancePercent: 3.7 },
  { accountCode: '5500', accountNameEn: 'Gross Profit Margin', accountNameAr: 'إجمالي الربح التجاري', currentPeriodSar: 8852492, priorPeriodSar: 7610700, varianceSar: 1241792, variancePercent: 16.3 },
  { accountCode: '6000', accountNameEn: 'Store Labor, Wages & Staff Benefits', accountNameAr: 'الرواتب والأجور والمزايا التشغيلية', currentPeriodSar: -2777252, priorPeriodSar: -2647200, varianceSar: -130052, variancePercent: 4.9 },
  { accountCode: '6500', accountNameEn: 'Direct Branch Operating Expenses (Rent/Util)', accountNameAr: 'المصاريف التشغيلية للفروع (الإيجار والمرافق)', currentPeriodSar: -1859767, priorPeriodSar: -1820000, varianceSar: -39767, variancePercent: 2.2 },
  { accountCode: '7000', accountNameEn: 'EBITDA (Operational Profit)', accountNameAr: 'الأرباح التشغيلية قبل الفوائد والضرائب (EBITDA)', currentPeriodSar: 4215473, priorPeriodSar: 3143500, varianceSar: 1071973, variancePercent: 34.1 },
];
