import { MobileAppDefinition, PushNotificationRecord } from './types';

export const ENTERPRISE_MOBILE_APPS: MobileAppDefinition[] = [
  {
    id: 'OWNER_APP',
    appNameEn: 'OmniOwner Executive Live',
    appNameAr: 'تطبيق المالك والرئيس التنفيذي المباشر',
    targetUserEn: 'Franchise Owners, Board of Directors & C-Level Executives',
    targetUserAr: 'ملاك المطاعم، مجالس الإدارة، والرؤساء التنفيذيين',
    appIcon: 'Crown',
    version: 'v2.6.4 (Build 890)',
    bundleId: 'com.omnipos.enterprise.owner',
    offlineCapable: true,
    biometricSupported: true,
    features: [
      { titleEn: 'Real-Time GMV & Margin Ticker', titleAr: 'مؤشر الإيرادات والأرباح الفوري', descriptionEn: 'Streaming live receipts and P&L by second.', descriptionAr: 'بث حي ومباشر للمبيعات وصافي الأرباح لحظة بلحظة.' },
      { titleEn: 'Biometric Payout Approvals', titleAr: 'اعتماد المدفوعات بالبصمة', descriptionEn: 'FaceID / TouchID multi-sig authorization.', descriptionAr: 'تفويض التحويلات البنكية والمصروفات بالبصمة البيومترية.' },
      { titleEn: 'Branch Video & Telemetry Feed', titleAr: 'بث الكاميرات ومؤشرات الفروع', descriptionEn: 'Instant visual check and occupancy radar.', descriptionAr: 'متابعة نسبة إشغال الصالة والكاميرات المباشرة.' },
    ],
    activeInstalls: 340,
    crashFreeRatePercent: 99.98,
    syncLatencyMs: 24,
    quickActions: ['Instant Net P&L Today', 'View Active Cash Drawers', 'Approve Procurement PO > 50k SAR', 'Send Broadcast to All GMs'],
  },
  {
    id: 'MANAGER_APP',
    appNameEn: 'OmniManager Store Command',
    appNameAr: 'تطبيق مدير الفرع والعمليات اليومية',
    targetUserEn: 'Store General Managers & Shift Supervisors',
    targetUserAr: 'مدراء الفروع، مشرفو الورديات، ورؤساء الأقسام',
    appIcon: 'Building',
    version: 'v2.6.4 (Build 890)',
    bundleId: 'com.omnipos.enterprise.manager',
    offlineCapable: true,
    biometricSupported: true,
    features: [
      { titleEn: 'Shift & Safe Float Balancing', titleAr: 'إقفال الوردية وتوازن الخزينة', descriptionEn: 'Blind cash drops and end-of-shift reconciliation.', descriptionAr: 'تسوية الصندوق وجرد العهدة النقدية بنهاية الشفت.' },
      { titleEn: 'Staff Attendance & Schedule Overrides', titleAr: 'سجل الحضور وتعديل الجداول', descriptionEn: 'Geo-fenced clock in/out verification.', descriptionAr: 'التحقق من حضور الموظفين عبر النطاق الجغرافي (GPS).' },
      { titleEn: 'Instant Item 86 / Stock Out Toggle', titleAr: 'إيقاف الأصناف فور نفادها (86)', descriptionEn: 'Syncs with POS, KDS, App and Delivery Aggregators.', descriptionAr: 'إيقاف الصنف بلمسة واحدة في كافة القنوات وتطبيقات التوصيل.' },
    ],
    activeInstalls: 1420,
    crashFreeRatePercent: 99.95,
    syncLatencyMs: 18,
    quickActions: ['Open Daily Shift', 'Override Cashier Discount', 'Receive Commissary Shipment', 'Trigger Emergency Kitchen Hold'],
  },
  {
    id: 'KITCHEN_APP',
    appNameEn: 'OmniKitchen KDS Display & Expediter',
    appNameAr: 'تطبيق المطبخ وشاشات الطهي ومسؤول الترحيل',
    targetUserEn: 'Line Cooks, Prep Stations & Head Expediters',
    targetUserAr: 'طهاة الخط الساخن، محطات التحضير، ومسؤولو الترحيل',
    appIcon: 'Flame',
    version: 'v2.6.0 (Build 812)',
    bundleId: 'com.omnipos.enterprise.kitchen',
    offlineCapable: true,
    biometricSupported: false,
    features: [
      { titleEn: 'CRDT Decentralized Sync', titleAr: 'مزامنة لامركزية فورية (CRDT)', descriptionEn: 'Zero delay order bumping between hot and cold lines.', descriptionAr: 'ترحيل متزامن بين محطات القلي والمشواة والتجميع.' },
      { titleEn: 'Recipe BOM & Ingredient Visualizer', titleAr: 'عرض تفاصيل الوصفة والحساسيات', descriptionEn: 'Step-by-step plating and allergen alerts.', descriptionAr: 'دليل التحضير وخطوات التقديم وتنبيهات الحساسية.' },
    ],
    activeInstalls: 2890,
    crashFreeRatePercent: 99.99,
    syncLatencyMs: 8,
    quickActions: ['Bump Next Ticket', 'Recall Last Order', 'Mark Prep Batch Complete', 'Sound Rush Alert'],
  },
  {
    id: 'CASHIER_APP',
    appNameEn: 'OmniPOS Mobile Handheld Register',
    appNameAr: 'تطبيق الكاشير المتنقل ونقاط البيع المحمولة',
    targetUserEn: 'Front Cashiers & Drive-thru Line Busters',
    targetUserAr: 'كاشيرات الاستقبال وخدمة طابور السيارات (Line Busting)',
    appIcon: 'LayoutGrid',
    version: 'v2.6.4 (Build 890)',
    bundleId: 'com.omnipos.enterprise.cashier',
    offlineCapable: true,
    biometricSupported: true,
    features: [
      { titleEn: 'Offline ZATCA QR Generator', titleAr: 'توليد فواتير زاتكا بدون إنترنت', descriptionEn: 'Full cryptographic ECDSA stamping locally.', descriptionAr: 'توقيع إلكتروني وتوليد رمز الاستجابة السريعة فورياً.' },
      { titleEn: 'Integrated Mada Tap-on-Phone', titleAr: 'دفع مدى عبر لمس الهاتف (NFC)', descriptionEn: 'Accept contactless cards directly on device.', descriptionAr: 'قبول بطاقات مدى وأبل باي عبر تقنية NFC المباشرة.' },
    ],
    activeInstalls: 5120,
    crashFreeRatePercent: 99.96,
    syncLatencyMs: 12,
    quickActions: ['New Fast Order', 'Scan Customer Barcode', 'Split Bill by Seat', 'Process NFC Payment'],
  },
  {
    id: 'WAITER_APP',
    appNameEn: 'OmniWaiter Tableside Ordering & Pay',
    appNameAr: 'تطبيق النادل والطلب والدفع عند الطاولة',
    targetUserEn: 'Dining Room Waitstaff & Sommeliers',
    targetUserAr: 'طاقم خدمة الصالة ومسؤولو الضيافة',
    appIcon: 'UtensilsCrossed',
    version: 'v2.6.2 (Build 840)',
    bundleId: 'com.omnipos.enterprise.waiter',
    offlineCapable: true,
    biometricSupported: false,
    features: [
      { titleEn: 'Interactive Floor & Table Map', titleAr: 'خريطة الطاولات التفاعلية', descriptionEn: 'Live guest count, order stage, and payment status.', descriptionAr: 'حالة الطاولة وعدد الضيوف ومراحل تقديم الأطباق.' },
      { titleEn: 'Tableside Modifier Upselling', titleAr: 'اقتراحات البيع الإضافي عند الطاولة', descriptionEn: 'AI recommended wine and dessert pairings.', descriptionAr: 'توصيات ذكية للمقبلات والمشروبات والحلويات.' },
    ],
    activeInstalls: 3840,
    crashFreeRatePercent: 99.97,
    syncLatencyMs: 14,
    quickActions: ['Seat Table #12', 'Add Round of Drinks', 'Print Pre-Bill Check', 'Transfer Table to Patio'],
  },
  {
    id: 'DRIVER_APP',
    appNameEn: 'OmniDriver Cold-Chain Delivery & GPS',
    appNameAr: 'تطبيق سائق التوصيل والتتبع المباشر GPS',
    targetUserEn: 'Internal Fleet Drivers & Logistics Couriers',
    targetUserAr: 'سائقو الأسطول الداخلي ومناديب التوصيل المباشر',
    appIcon: 'Navigation',
    version: 'v2.5.8 (Build 790)',
    bundleId: 'com.omnipos.enterprise.driver',
    offlineCapable: true,
    biometricSupported: false,
    features: [
      { titleEn: 'Turn-by-Turn Route Optimization', titleAr: 'توجيه المسار الذكي والخرائط', descriptionEn: 'Batched multi-drop delivery routing.', descriptionAr: 'تجميع ذكي لعدة طلبات في مسار توصيل واحد.' },
      { titleEn: 'Temperature Sensor Telemetry', titleAr: 'مراقبة حرارة الصندوق المبرد', descriptionEn: 'IoT thermal logging for food safety compliance.', descriptionAr: 'تسجيل درجة حرارة الحافظة لضمان سلامة الغذاء.' },
    ],
    activeInstalls: 1980,
    crashFreeRatePercent: 99.92,
    syncLatencyMs: 32,
    quickActions: ['Accept Next Dispatch', 'Call Customer via Masked VoIP', 'Confirm Doorstep Delivery', 'Upload Signature & Photo'],
  },
  {
    id: 'INVENTORY_APP',
    appNameEn: 'OmniStock Scanner & Cycle Count',
    appNameAr: 'تطبيق مستودع المخزون والجرد السريع بالباركود',
    targetUserEn: 'Warehouse Managers & Inventory Auditors',
    targetUserAr: 'أمناء المستودعات ومدققو الجرد الدوري',
    appIcon: 'Boxes',
    version: 'v2.6.1 (Build 825)',
    bundleId: 'com.omnipos.enterprise.inventory',
    offlineCapable: true,
    biometricSupported: false,
    features: [
      { titleEn: 'Camera & Zebra Barcode Scanner', titleAr: 'مسح الباركود بالكاميرا والقارئ الضوئي', descriptionEn: 'Rapid barcode, QR and RFID lot tag capture.', descriptionAr: 'جرد فوري لباركود المنتجات ودفعات الإنتاج.' },
      { titleEn: 'Blind Cycle Count Verification', titleAr: 'الجرد الأعمى ومطابقة الفروقات', descriptionEn: 'Instant discrepancy audit against theoretical ledger.', descriptionAr: 'كشف الفروقات بين الرصيد الدفتري والفعلي.' },
    ],
    activeInstalls: 920,
    crashFreeRatePercent: 99.94,
    syncLatencyMs: 15,
    quickActions: ['Start Daily Fast Count', 'Receive Vendor PO Goods', 'Log Kitchen Spoilage Scrap', 'Scan Bin Location Barcode'],
  },
  {
    id: 'SUPPLIER_APP',
    appNameEn: 'OmniVendor Supplier & PO Portal',
    appNameAr: 'تطبيق وموردين وسلسلة الإمداد (B2B)',
    targetUserEn: 'Raw Material Vendors & Packaging Distributors',
    targetUserAr: 'موردو المواد الغذائية وشركات التعبئة والتغليف',
    appIcon: 'ShoppingCart',
    version: 'v2.4.9 (Build 720)',
    bundleId: 'com.omnipos.enterprise.supplier',
    offlineCapable: false,
    biometricSupported: true,
    features: [
      { titleEn: 'Automated 3-Way PO Matching', titleAr: 'المطابقة الثلاثية لأوامر الشراء', descriptionEn: 'Instant matching between PO, GRN, and Invoice.', descriptionAr: 'مطابقة أمر الشراء مع محضر الاستلام والفاتورة.' },
      { titleEn: 'Early Payment Discount Tracker', titleAr: 'سداد المستحقات والخصم المبكر', descriptionEn: 'Live tracking of invoices and bank wire schedules.', descriptionAr: 'متابعة مواعيد الصرف وحوالات البنوك المعتمدة.' },
    ],
    activeInstalls: 480,
    crashFreeRatePercent: 99.91,
    syncLatencyMs: 28,
    quickActions: ['Confirm Purchase Order #892', 'Submit Dispatch ASN', 'Download Remittance Advice', 'Update Price Catalogue'],
  },
  {
    id: 'CUSTOMER_APP',
    appNameEn: 'OmniRewards Guest Loyalty & Mobile Order',
    appNameAr: 'تطبيق العميل للولاء والطلب المسبق والمحفظة',
    targetUserEn: 'Dine-in Guests, Delivery Customers & Loyalty Members',
    targetUserAr: 'ضيوف المطعم، عملاء التوصيل، وأعضاء برنامج الولاء',
    appIcon: 'Users',
    version: 'v3.1.2 (Build 1204)',
    bundleId: 'com.omnipos.enterprise.customer',
    offlineCapable: true,
    biometricSupported: true,
    features: [
      { titleEn: 'Table QR Ordering & Apple Pay', titleAr: 'الطلب بمسح رمز الطاولة والدفع الفوري', descriptionEn: 'Zero-wait dining room ordering and checkout.', descriptionAr: 'طلب فوري من الطاولة ودفع آمن عبر Apple Pay.' },
      { titleEn: 'OmniWallet Stored Value & Gift Cards', titleAr: 'المحفظة الرقمية وبطاقات الهدايا', descriptionEn: 'Instant reload with cashback and friend transfers.', descriptionAr: 'شحن رصيد المحفظة مع كاش باك وإهداء الأصدقاء.' },
    ],
    activeInstalls: 145000,
    crashFreeRatePercent: 99.98,
    syncLatencyMs: 20,
    quickActions: ['Order Pickup at Olaya', 'Scan Table QR #4', 'Reload Wallet +200 SAR', 'Redeem 500 Loyalty Points'],
  },
];

export const RECENT_PUSH_NOTIFICATIONS: PushNotificationRecord[] = [
  {
    id: 'PUSH-01',
    targetApp: 'MANAGER_APP',
    titleEn: 'Stock Out Alert: Fresh Brioche Buns (Olaya)',
    titleAr: 'تنبيه نفاد المخزون: خبز البريوش الطازج (فرع العليا)',
    bodyEn: 'Inventory dropped below safety buffer (12 packs remaining). Automated commissary transfer recommended.',
    bodyAr: 'انخفض المخزون عن حد الأمان (متبقي 12 حزمة). نوصي بتأكيد استلام شحنة المطبخ المركزي.',
    deepLink: 'omnimanager://inventory/transfer/BR-01',
    sentAt: '2026-08-27 13:42:10',
    deliveryStatus: 'DELIVERED',
  },
  {
    id: 'PUSH-02',
    targetApp: 'CUSTOMER_APP',
    titleEn: 'Your Artisan Coffee is Ready for Pickup! ☕',
    titleAr: 'قهوتك المختصة جاهزة للاستلام الآن! ☕',
    bodyEn: 'Your order #492 is freshly brewed and ready at the Olaya drive-thru pickup window.',
    bodyAr: 'طلبك رقم 492 جاهز بالكامل في نافذة الاستلام السريع بفرع العليا.',
    deepLink: 'omnirewards://orders/track/492',
    sentAt: '2026-08-27 13:40:00',
    deliveryStatus: 'READ',
  },
];
