import { GlobalReleaseGate } from './types';

export const INITIAL_GLOBAL_RELEASE_GATES: GlobalReleaseGate[] = [
  {
    id: 'GATE-01',
    stepNumber: 1,
    titleEn: 'API Contract & Protocol Freeze',
    titleAr: 'تجميد واجهات برمجة التطبيقات (API Freeze)',
    descriptionEn: 'All REST, GraphQL, AsyncAPI, and gRPC endpoints are locked. Zero breaking changes permitted.',
    descriptionAr: 'قفل جميع الواجهات البرمجية والعقود ومنع أي تغييرات تكسر التوافق.',
    status: 'PASSED',
    signedOffBy: 'API Governance Board Lead',
    signedOffAt: '2026-08-25T14:30:00Z',
    mandatory: true,
    artifacts: ['OpenAPI_v3.1_Snapshot.json', 'AsyncAPI_Registry_Locked.yaml', 'Proto3_Descriptor.bin'],
  },
  {
    id: 'GATE-02',
    stepNumber: 2,
    titleEn: 'Database Schema & Migration Freeze',
    titleAr: 'تجميد مخطط وقواعد البيانات (Schema Freeze)',
    descriptionEn: 'Database tables, partitioned structures, and DDL migrations locked. Zero schema modifications allowed.',
    descriptionAr: 'قفل جداول قاعدة البيانات ومخططات DDL ومنع أي تعديل هيكلي.',
    status: 'PASSED',
    signedOffBy: 'Principal Database Architect',
    signedOffAt: '2026-08-25T16:00:00Z',
    mandatory: true,
    artifacts: ['Schema_Hash_SHA256.txt', 'Partition_Catalog_2026.sql', 'Migration_Lock_Pass.log'],
  },
  {
    id: 'GATE-03',
    stepNumber: 3,
    titleEn: 'Feature & Code Scope Freeze',
    titleAr: 'تجميد الميزات ونطاق الكود (Feature Freeze)',
    descriptionEn: 'Codebase branch is in strict feature freeze mode. Only blocker defect remediations permitted.',
    descriptionAr: 'قفل الفرع الرئيسي وتجميد إضافة ميزات جديدة مع قبول إصلاحات العيوب الحرجة فقط.',
    status: 'PASSED',
    signedOffBy: 'Head of Engineering',
    signedOffAt: '2026-08-26T09:00:00Z',
    mandatory: true,
    artifacts: ['Git_Tag_Freeze_v1.0.0.txt', 'Branch_Protection_Rules.json'],
  },
  {
    id: 'GATE-04',
    stepNumber: 4,
    titleEn: 'Comprehensive Security & Pen-Test Review',
    titleAr: 'المراجعة الأمنية الشاملة واختبار الاختراق',
    descriptionEn: 'OWASP ASVS L4 audit, Red Team penetration test report, and Zero Secret scan signed off.',
    descriptionAr: 'اعتماد تدقيق OWASP ASVS L4 وتقرير الفريق الأحمر لفحص الاختراق والتأكد من خلو الشيفرة من الثغرات.',
    status: 'PASSED',
    signedOffBy: 'Chief Information Security Officer (CISO)',
    signedOffAt: '2026-08-26T11:45:00Z',
    mandatory: true,
    artifacts: ['PenTest_Clean_Report_2026.pdf', 'ASVS_L4_Attestation.xml', 'Secret_Scan_Zero_Report.json'],
  },
  {
    id: 'GATE-05',
    stepNumber: 5,
    titleEn: 'Performance & SLA Latency Review',
    titleAr: 'مراجعة الأداء ومطابقة اتفاقية مستوى الخدمة',
    descriptionEn: 'Verification of 8,920 TPS, P99 latency < 15ms, and 100,000 POS device scale benchmarks.',
    descriptionAr: 'التحقق من تحقيق 8920 معاملة/ثانية وزمن استجابة أقل من 15 مللي ثانية ومحاكاة 100 ألف جهاز.',
    status: 'PASSED',
    signedOffBy: 'Performance Engineering Lead',
    signedOffAt: '2026-08-26T14:15:00Z',
    mandatory: true,
    artifacts: ['JMeter_10k_Branches_Report.html', 'K6_Distributed_Load_Summary.json', 'APM_FlameGraph_Trace.svg'],
  },
  {
    id: 'GATE-06',
    stepNumber: 6,
    titleEn: 'Documentation & Operational Runbooks Review',
    titleAr: 'مراجعة التوثيق وكتيبات التشغيل الميدانية',
    descriptionEn: 'Architectural documentation, on-call runbooks, and ZATCA compliance procedures validated.',
    descriptionAr: 'فحص الأدلة المعمارية، كتيبات المناوبة والتدخل السريع، وإجراءات هيئة الزكاة والضريبة.',
    status: 'PASSED',
    signedOffBy: 'Site Reliability Engineering Lead',
    signedOffAt: '2026-08-26T17:00:00Z',
    mandatory: true,
    artifacts: ['SRE_OnCall_Playbook_v1.0.pdf', 'ZATCA_Audit_Trail_Handbook.pdf'],
  },
  {
    id: 'GATE-07',
    stepNumber: 7,
    titleEn: 'Disaster Recovery Live Drill (RPO=0, RTO < 3s)',
    titleAr: 'تمرين التعافي من الكوارث الحي (RPO=0 و RTO < 3s)',
    descriptionEn: 'Simulated loss of primary cloud region with instantaneous failover and zero data loss.',
    descriptionAr: 'محاكاة انقطاع المنطقة السحابية الرئيسية والتحول الفوري للنسخة الاحتياطية دون أي فقدان للبيانات.',
    status: 'PASSED',
    signedOffBy: 'Enterprise DR Incident Commander',
    signedOffAt: '2026-08-27T08:00:00Z',
    mandatory: true,
    artifacts: ['DR_Drill_Execution_Log.txt', 'Data_Integrity_Checksums_Match.json'],
  },
  {
    id: 'GATE-08',
    stepNumber: 8,
    titleEn: 'Point-in-Time Backup & Restore Validation',
    titleAr: 'التحقق من استعادة النسخ الاحتياطية اللحظية (PITR)',
    descriptionEn: 'Restoration of 50TB database cluster to exact second with byte-for-byte checksum verification.',
    descriptionAr: 'استرجاع قاعدة بيانات بحجم 50 تيرابايت لثانية محددة والتحقق من تطابق البصمة الرقمية للبيانات.',
    status: 'PASSED',
    signedOffBy: 'Principal Storage & DBA Lead',
    signedOffAt: '2026-08-27T08:45:00Z',
    mandatory: true,
    artifacts: ['PITR_Verification_Success.log', 'MD5_Checksum_Verification.csv'],
  },
  {
    id: 'GATE-09',
    stepNumber: 9,
    titleEn: 'Multi-Region Active-Active Failover Test',
    titleAr: 'اختبار التحويل التلقائي بين المناطق المتعددة',
    descriptionEn: 'Global traffic routing via Anycast DNS and BGP failover under full simulated production load.',
    descriptionAr: 'اختبار توجيه حركة المرور العالمية عبر Anycast DNS و BGP تحت الحمل الإنتاجي الكامل.',
    status: 'PASSED',
    signedOffBy: 'Cloud Infrastructure Architect',
    signedOffAt: '2026-08-27T09:15:00Z',
    mandatory: true,
    artifacts: ['DNS_Propagation_Check.log', 'MultiRegion_Latency_Matrix.json'],
  },
  {
    id: 'GATE-10',
    stepNumber: 10,
    titleEn: 'Long-Running Soak & Stability Test Sign-Off',
    titleAr: 'اعتماد اختبار التحمل طويل الأمد والاستقرار',
    descriptionEn: 'Confirmed 30-day stability with 0 memory leaks, 99.999% uptime, and consistent queue depth.',
    descriptionAr: 'تأكيد استقرار النظام لمدة 30 يومًا بدون تسريب في الذاكرة وبنسبة توفر 99.999%.',
    status: 'PASSED',
    signedOffBy: 'Quality Assurance Director',
    signedOffAt: '2026-08-27T09:30:00Z',
    mandatory: true,
    artifacts: ['Soak_Test_30Day_Telemetry.csv', 'Heap_Growth_Regression_Flat.png'],
  },
  {
    id: 'GATE-11',
    stepNumber: 11,
    titleEn: 'Final Release Candidate (RC) Certification',
    titleAr: 'اعتماد النسخة النهائية المرشحة للإطلاق (RC-1)',
    descriptionEn: 'Tag v1.0.0-RC1 created, container images signed with Cosign, SBOM embedded in enterprise registry.',
    descriptionAr: 'توليد الوسم v1.0.0-RC1 وتوقيع حاويات الإنتاج رقمياً وتضمين وثيقة SBOM في المستودع المؤسسي.',
    status: 'PASSED',
    signedOffBy: 'Release Management Officer',
    signedOffAt: '2026-08-27T09:45:00Z',
    mandatory: true,
    artifacts: ['Cosign_Signature_Verify.pem', 'Docker_Image_Digest_SHA256.txt', 'SBOM_SPDX_v2.3.json'],
  },
  {
    id: 'GATE-12',
    stepNumber: 12,
    titleEn: 'General Availability (GA) Global Deployment Switch',
    titleAr: 'تفعيل الإطلاق العالمي للإنتاج (General Availability)',
    descriptionEn: 'Global traffic shift to production cluster. Multi-tenant live operations green across all GCC branches.',
    descriptionAr: 'تحويل حركة المرور العالمية إلى البيئة الإنتاجية وبدء العمليات الحية في جميع الفروع.',
    status: 'PASSED',
    signedOffBy: 'Chief Technology Officer (CTO)',
    signedOffAt: '2026-08-27T10:00:00Z',
    mandatory: true,
    artifacts: ['Global_Production_Deployment_Certificate.pdf', 'Live_Traffic_100_Percent.log'],
  },
];
