import { KpiMetric, DashboardViewConfig, ScheduledReport, BiDashboardRole } from './types';

export const ENTERPRISE_KPIS: KpiMetric[] = [
  {
    id: 'GMV',
    nameEn: 'Gross Merchandise Value (GMV)',
    nameAr: 'إجمالي قيمة البضائع (GMV)',
    category: 'REVENUE',
    value: 14258900,
    formattedValue: '14,258,900 SAR',
    unit: 'SAR',
    changePercent: 14.8,
    trend: 'UP',
    isPositive: true,
    target: 13500000,
    sparkline: [11.2, 11.8, 12.4, 13.1, 13.9, 14.1, 14.25],
    descriptionEn: 'Total unadjusted gross revenue across all sales channels before deductions.',
    descriptionAr: 'إجمالي قيمة المبيعات عبر جميع القنوات قبل الخصومات والاسترجاع.',
  },
  {
    id: 'NET_SALES',
    nameEn: 'Net Sales',
    nameAr: 'صافي المبيعات',
    category: 'REVENUE',
    value: 12398450,
    formattedValue: '12,398,450 SAR',
    unit: 'SAR',
    changePercent: 12.4,
    trend: 'UP',
    isPositive: true,
    target: 11800000,
    sparkline: [9.8, 10.4, 11.0, 11.6, 12.0, 12.2, 12.39],
    descriptionEn: 'Gross sales minus discounts, loyalty redemptions, and refunded voids.',
    descriptionAr: 'المبيعات الفعلية بعد خصم العروض وبرامج الولاء والطلبات الملغاة.',
  },
  {
    id: 'GROSS_PROFIT',
    nameEn: 'Gross Profit',
    nameAr: 'إجمالي الربح التجاري',
    category: 'REVENUE',
    value: 8430946,
    formattedValue: '8,430,946 SAR',
    unit: 'SAR',
    changePercent: 15.2,
    trend: 'UP',
    isPositive: true,
    target: 8000000,
    sparkline: [6.8, 7.2, 7.5, 7.9, 8.1, 8.3, 8.43],
    descriptionEn: 'Net sales minus direct Cost of Goods Sold (COGS).',
    descriptionAr: 'صافي المبيعات مطروحاً منها تكلفة البضاعة المباعة المباشرة.',
  },
  {
    id: 'EBITDA',
    nameEn: 'EBITDA Margin',
    nameAr: 'الأرباح قبل الفوائد والضرائب والإهلاك (EBITDA)',
    category: 'REVENUE',
    value: 28.4,
    formattedValue: '28.4%',
    unit: '%',
    changePercent: 3.2,
    trend: 'UP',
    isPositive: true,
    target: 25.0,
    sparkline: [24.1, 25.0, 25.8, 26.5, 27.2, 27.9, 28.4],
    descriptionEn: 'Operating profitability indicator reflecting core operational health.',
    descriptionAr: 'هامش الربحية التشغيلية الصافية ويعكس الكفاءة المؤسسية للشبكة.',
  },
  {
    id: 'FOOD_COST_PERCENT',
    nameEn: 'Food Cost % (COGS)',
    nameAr: 'نسبة تكلفة الأغذية (Food Cost %)',
    category: 'COST',
    value: 28.6,
    formattedValue: '28.6%',
    unit: '%',
    changePercent: -1.8,
    trend: 'DOWN',
    isPositive: true,
    target: 30.0,
    sparkline: [31.2, 30.8, 30.1, 29.5, 29.1, 28.9, 28.6],
    descriptionEn: 'Ingredient and packaging cost divided by total net sales.',
    descriptionAr: 'تكلفة المكونات والتغليف منسوبة إلى إجمالي صافي المبيعات.',
  },
  {
    id: 'LABOR_COST_PERCENT',
    nameEn: 'Labor Cost %',
    nameAr: 'نسبة تكلفة العمالة والرواتب',
    category: 'COST',
    value: 22.4,
    formattedValue: '22.4%',
    unit: '%',
    changePercent: -0.9,
    trend: 'DOWN',
    isPositive: true,
    target: 24.0,
    sparkline: [24.5, 24.0, 23.6, 23.1, 22.8, 22.5, 22.4],
    descriptionEn: 'Direct and indirect frontline staff wages relative to revenue.',
    descriptionAr: 'تكاليف الرواتب والمزايا التشغيلية منسوبة إلى إجمالي الإيرادات.',
  },
  {
    id: 'PRIME_COST',
    nameEn: 'Prime Cost (Food + Labor)',
    nameAr: 'التكلفة الأساسية (المواد + العمالة)',
    category: 'COST',
    value: 51.0,
    formattedValue: '51.0%',
    unit: '%',
    changePercent: -2.7,
    trend: 'DOWN',
    isPositive: true,
    target: 55.0,
    sparkline: [55.7, 54.8, 53.7, 52.6, 51.9, 51.4, 51.0],
    descriptionEn: 'Industry gold standard: Combined COGS and Labor cost (Target < 55%).',
    descriptionAr: 'المعيار الذهبي لقطاع المطاعم: مجموع تكلفة الأغذية والعمالة (المستهدف < 55%).',
  },
  {
    id: 'WASTE_PERCENT',
    nameEn: 'Inventory Waste %',
    nameAr: 'نسبة الهدر والفاقد بالمخزون',
    category: 'COST',
    value: 1.15,
    formattedValue: '1.15%',
    unit: '%',
    changePercent: -0.45,
    trend: 'DOWN',
    isPositive: true,
    target: 2.0,
    sparkline: [1.9, 1.75, 1.6, 1.45, 1.3, 1.2, 1.15],
    descriptionEn: 'Expired, damaged, or unrecorded variance as a percentage of usage.',
    descriptionAr: 'نسبة المواد التالفة أو المنتهية الصلاحية منسوبة للاستهلاك الفعلي.',
  },
  {
    id: 'AVG_TICKET',
    nameEn: 'Average Ticket / Order Value (AOV)',
    nameAr: 'متوسط قيمة الفاتورة (AOV)',
    category: 'REVENUE',
    value: 78.4,
    formattedValue: '78.4 SAR',
    unit: 'SAR',
    changePercent: 6.8,
    trend: 'UP',
    isPositive: true,
    target: 72.0,
    sparkline: [71.5, 73.0, 74.2, 75.8, 76.9, 77.8, 78.4],
    descriptionEn: 'Average spend per completed order across dine-in, drive-thru, and delivery.',
    descriptionAr: 'متوسط إنفاق العميل لكل طلب مكتمل عبر كافة القنوات.',
  },
  {
    id: 'ORDERS_PER_HOUR',
    nameEn: 'Peak Orders Per Hour (OPH)',
    nameAr: 'معدل الطلبات في ساعة الذروة (OPH)',
    category: 'OPERATIONS',
    value: 1420,
    formattedValue: '1,420 ord/hr',
    unit: 'ord/hr',
    changePercent: 18.3,
    trend: 'UP',
    isPositive: true,
    target: 1200,
    sparkline: [1100, 1180, 1250, 1310, 1370, 1400, 1420],
    descriptionEn: 'Aggregate peak throughput handled concurrently across active branches.',
    descriptionAr: 'إجمالي الطاقة الاستيعابية للطلبات في ساعات الذروة عبر الفروع.',
  },
  {
    id: 'TABLE_TURNOVER',
    nameEn: 'Table Turnover Rate',
    nameAr: 'معدل دوران الطاولات',
    category: 'OPERATIONS',
    value: 3.8,
    formattedValue: '3.8 turns/day',
    unit: 'turns',
    changePercent: 8.5,
    trend: 'UP',
    isPositive: true,
    target: 3.5,
    sparkline: [3.1, 3.2, 3.4, 3.5, 3.6, 3.75, 3.8],
    descriptionEn: 'Average times a physical dining table is occupied and served per day.',
    descriptionAr: 'متوسط عدد المرات التي تشغل فيها الطاولة ويتم خدمتها يومياً.',
  },
  {
    id: 'KITCHEN_SLA',
    nameEn: 'Kitchen Prep SLA Adherence',
    nameAr: 'الالتزام بوقت تحضير المطبخ (SLA)',
    category: 'EFFICIENCY',
    value: 96.8,
    formattedValue: '96.8%',
    unit: '%',
    changePercent: 2.4,
    trend: 'UP',
    isPositive: true,
    target: 95.0,
    sparkline: [93.2, 94.0, 94.8, 95.5, 96.0, 96.5, 96.8],
    descriptionEn: 'Percentage of orders prepared and bumped in KDS under the 6-minute threshold.',
    descriptionAr: 'نسبة الطلبات المحضرة والمعلمة كجاهزة في المطبخ في أقل من 6 دقائق.',
  },
  {
    id: 'CASH_FLOW',
    nameEn: 'Operating Cash Flow (OCF)',
    nameAr: 'التدفق النقدي التشغيلي',
    category: 'REVENUE',
    value: 4890200,
    formattedValue: '4,890,200 SAR',
    unit: 'SAR',
    changePercent: 11.2,
    trend: 'UP',
    isPositive: true,
    target: 4500000,
    sparkline: [4.1, 4.25, 4.4, 4.6, 4.72, 4.81, 4.89],
    descriptionEn: 'Real net cash generated from day-to-day restaurant operations.',
    descriptionAr: 'السيولة النقدية الصافية المحققة من العمليات اليومية الفعلية.',
  },
  {
    id: 'INVENTORY_VALUE',
    nameEn: 'Active Total Inventory Valuation',
    nameAr: 'إجمالي قيمة المخزون الحالي',
    category: 'COST',
    value: 3450000,
    formattedValue: '3,450,000 SAR',
    unit: 'SAR',
    changePercent: -3.5,
    trend: 'DOWN',
    isPositive: true,
    target: 3600000,
    sparkline: [3.8, 3.72, 3.65, 3.58, 3.52, 3.48, 3.45],
    descriptionEn: 'Real-time FIFO valuation of raw materials across central warehouses and branches.',
    descriptionAr: 'التقييم الفعلي للمخزون وفق طريقة الوارد أولاً يصرف أولاً (FIFO).',
  },
  {
    id: 'CLV',
    nameEn: 'Customer Lifetime Value (CLV)',
    nameAr: 'القيمة الدائمة للعميل (CLV)',
    category: 'CUSTOMER',
    value: 1240,
    formattedValue: '1,240 SAR',
    unit: 'SAR',
    changePercent: 19.5,
    trend: 'UP',
    isPositive: true,
    target: 1000,
    sparkline: [980, 1020, 1070, 1120, 1170, 1210, 1240],
    descriptionEn: 'Projected net revenue attributed to the entire future relationship with a guest.',
    descriptionAr: 'القيمة المالية المتوقعة لإجمالي تعاملات العميل طوال فترة ولائه للمطعم.',
  },
  {
    id: 'LOYALTY_GROWTH',
    nameEn: 'Loyalty Member Active Growth',
    nameAr: 'نمو أعضاء برنامج الولاء النشطين',
    category: 'CUSTOMER',
    value: 34.2,
    formattedValue: '+34.2%',
    unit: '%',
    changePercent: 8.1,
    trend: 'UP',
    isPositive: true,
    target: 25.0,
    sparkline: [22, 24.5, 27.0, 29.2, 31.5, 33.0, 34.2],
    descriptionEn: 'Month-over-month increase in transacting rewards members.',
    descriptionAr: 'الزيادة الشهرية في عدد العملاء النشطين مستخدمي برنامج المكافآت.',
  },
  {
    id: 'DELIVERY_PERF',
    nameEn: 'On-Time Delivery Rate',
    nameAr: 'نسبة التوصيل في الموعد المحدد',
    category: 'EFFICIENCY',
    value: 94.6,
    formattedValue: '94.6%',
    unit: '%',
    changePercent: 3.1,
    trend: 'UP',
    isPositive: true,
    target: 92.0,
    sparkline: [90.5, 91.2, 92.4, 93.1, 93.8, 94.2, 94.6],
    descriptionEn: 'Last-mile dispatch to doorstep completion under estimated SLA promise.',
    descriptionAr: 'نسبة الطلبات المسلمة لباب العميل ضمن التوقيت الموعود بدقة.',
  },
  {
    id: 'SALES_FORECAST',
    nameEn: 'AI 30-Day Sales Forecast',
    nameAr: 'التنبؤ الذكي بمبيعات الـ 30 يوماً القادمة',
    category: 'REVENUE',
    value: 16800000,
    formattedValue: '16,800,000 SAR',
    unit: 'SAR',
    changePercent: 17.8,
    trend: 'UP',
    isPositive: true,
    target: 15500000,
    sparkline: [13.5, 14.1, 14.8, 15.4, 15.9, 16.3, 16.8],
    descriptionEn: 'Machine learning ensemble forecast based on weather, seasonality, and events.',
    descriptionAr: 'تنبؤ قائم على خوارزميات التعلم الآلي يدمج المواسم والفعاليات والعوامل الجوية.',
  },
];

export const EXECUTIVE_DASHBOARD_CONFIGS: DashboardViewConfig[] = [
  {
    id: 'CEO',
    titleEn: 'Chief Executive Officer (CEO) Command Dashboard',
    titleAr: 'لوحة القيادة الاستراتيجية للرئيس التنفيذي (CEO)',
    personaEn: 'Strategic Growth, GMV, EBITDA, Brand Valuation & Market Expansion',
    personaAr: 'النمو الاستراتيجي، إجمالي المبيعات، الربحية، وتقييم العلامة التجارية',
    focusKpis: ['GMV', 'NET_SALES', 'EBITDA', 'SALES_FORECAST', 'CLV', 'LOYALTY_GROWTH'],
    recommendedCharts: ['REVENUE_TREND_AREA', 'EBITDA_WATERFALL', 'REGIONAL_MARKET_SHARE', 'AI_FORECAST_CURVE'],
    alertCount: 0,
  },
  {
    id: 'COO',
    titleEn: 'Chief Operating Officer (COO) Operations Command',
    titleAr: 'لوحة قيادة العمليات المركزية للرئيس التشغيلي (COO)',
    personaEn: 'Fleet Velocity, Kitchen SLAs, Prime Cost & Multi-Unit Uniformity',
    personaAr: 'سرعة الأسطول، التزام المطابخ بالوقت، التكلفة الأساسية، وكفاءة الوحدات',
    focusKpis: ['PRIME_COST', 'KITCHEN_SLA', 'DELIVERY_PERF', 'ORDERS_PER_HOUR', 'TABLE_TURNOVER', 'WASTE_PERCENT'],
    recommendedCharts: ['SLA_HEATMAP', 'LABOR_VS_SALES_BAR', 'BOTTLENECK_RADAR', 'PEAK_HOURLY_CURVE'],
    alertCount: 1,
  },
  {
    id: 'CFO',
    titleEn: 'Chief Financial Officer (CFO) Financial Suite',
    titleAr: 'لوحة القيادة المالية والتدفقات النقدية للرئيس المالي (CFO)',
    personaEn: 'Working Capital, Cash Flow, COGS, Tax & IFRS Profitability',
    personaAr: 'رأس المال العامل، التدفق النقدي، تكلفة البضاعة، والامتثال الضريبي والمعايير المحاسبية',
    focusKpis: ['GROSS_PROFIT', 'FOOD_COST_PERCENT', 'CASH_FLOW', 'INVENTORY_VALUE', 'NET_SALES', 'EBITDA'],
    recommendedCharts: ['CASH_FLOW_BRIDGE', 'COGS_BREAKDOWN_PIE', 'MARGIN_TREND_LINE', 'VAT_COMPLIANCE_BAR'],
    alertCount: 0,
  },
  {
    id: 'REGIONAL_MANAGER',
    titleEn: 'Regional Director Dashboard (Central, Western, Eastern)',
    titleAr: 'لوحة الإدارة الإقليمية (المنطقة الوسطى، الغربية، والشرقية)',
    personaEn: 'Branch Benchmark, Territorial Ranking & Geo Revenue Spread',
    personaAr: 'المقارنة المعيارية للفروع، تصنيف الأداء الجغرافي، ونمو المناطق',
    focusKpis: ['GMV', 'AVG_TICKET', 'ORDERS_PER_HOUR', 'PRIME_COST', 'DELIVERY_PERF', 'LOYALTY_GROWTH'],
    recommendedCharts: ['BRANCH_LEADERBOARD', 'REGIONAL_RADIAL', 'HOURLY_PACE_CHART'],
    alertCount: 2,
  },
  {
    id: 'BRANCH_MANAGER',
    titleEn: 'Store General Manager (GM) Shift Dashboard',
    titleAr: 'لوحة مدير الفرع والورديات اليومية',
    personaEn: 'Real-time Daily Target, Cashier Accuracy & Kitchen Speed',
    personaAr: 'الهدف اليومي المباشر، دقة الكاشير، سرعة المطبخ، ورضا الضيوف',
    focusKpis: ['NET_SALES', 'AVG_TICKET', 'TABLE_TURNOVER', 'KITCHEN_SLA', 'WASTE_PERCENT', 'LABOR_COST_PERCENT'],
    recommendedCharts: ['HOURLY_SALES_VELOCITY', 'STAFF_SCHEDULE_GRID', 'WASTE_LOG_STREAM'],
    alertCount: 1,
  },
  {
    id: 'KITCHEN_LEAD',
    titleEn: 'Executive Chef & Kitchen Operations Dashboard',
    titleAr: 'لوحة الشيف التنفيذي وإدارة المطبخ (KDS & Prep)',
    personaEn: 'Ticket Age, Prep Times, Recipe BOM Accuracy & Waste Control',
    personaAr: 'عمر الطلب، زمن الطهي، دقة الوصفات، والتحكم بالهدر الفعلي',
    focusKpis: ['KITCHEN_SLA', 'WASTE_PERCENT', 'FOOD_COST_PERCENT', 'ORDERS_PER_HOUR'],
    recommendedCharts: ['KDS_STATION_LOAD', 'COOK_TIME_DISTRIBUTION', 'ITEM_PREP_VELOCITY'],
    alertCount: 0,
  },
  {
    id: 'CASHIER_LEAD',
    titleEn: 'Front-of-House & Cashier Performance Hub',
    titleAr: 'لوحة رئيس الكاشيرات وخدمة العملاء',
    personaEn: 'Checkout Speed, Mada Terminal Uptime & Upsell Conversion',
    personaAr: 'سرعة التحصيل، استقرار أجهزة مدى، ونسبة نجاح البيع الإضافي',
    focusKpis: ['AVG_TICKET', 'ORDERS_PER_HOUR', 'NET_SALES', 'LOYALTY_GROWTH'],
    recommendedCharts: ['CASHIER_SPEED_RANK', 'PAYMENT_SPLIT_PIE', 'UPSELL_CONVERSION_BAR'],
    alertCount: 0,
  },
  {
    id: 'FRANCHISE_OWNER',
    titleEn: 'Franchise Investor & Multi-Unit Owner Portal',
    titleAr: 'بوابة المستثمر وأصحاب الامتياز التجاري (Franchisee)',
    personaEn: 'Royalty Accruals, Store ROI, Network Ranking & Supply Chain Sync',
    personaAr: 'رسوم الامتياز، العائد على الاستثمار، الترتيب بالشبكة، وتوريدات المركز',
    focusKpis: ['GMV', 'NET_SALES', 'GROSS_PROFIT', 'PRIME_COST', 'SALES_FORECAST'],
    recommendedCharts: ['ROYALTY_CALC_SUMMARY', 'NETWORK_BENCHMARK_CHART', 'PAYOUT_SCHEDULE'],
    alertCount: 0,
  },
  {
    id: 'OPERATIONS_DIRECTOR',
    titleEn: 'Global Supply Chain & Operations Directorate',
    titleAr: 'إدارة العمليات وسلسلة الإمداد اللوجستية المركزية',
    personaEn: 'Fill Rates, Central Kitchen Output, Fleet Health & 3-Way Matching',
    personaAr: 'معدل توريد الأصناف، إنتاج المطبخ المركزي، وكفاءة الأسطول اللوجستي',
    focusKpis: ['INVENTORY_VALUE', 'WASTE_PERCENT', 'PRIME_COST', 'DELIVERY_PERF', 'FOOD_COST_PERCENT'],
    recommendedCharts: ['SUPPLY_CHAIN_FLOW', 'FLEET_GPS_TELEMETRY', 'BOM_VARIANCE_MATRIX'],
    alertCount: 1,
  },
];

export const SCHEDULED_REPORTS_DEFAULT: ScheduledReport[] = [
  {
    id: 'REP-01',
    nameEn: 'Executive Daily Flash Financial & Sales Summary',
    nameAr: 'الملخص المالي والبيعي اليومي للإدارة العليا',
    frequency: 'DAILY',
    recipients: ['ceo@enterprise-pos.com', 'cfo@enterprise-pos.com'],
    format: 'PDF',
    lastRun: '2026-08-27 06:00:00',
    nextRun: '2026-08-28 06:00:00',
    status: 'ACTIVE',
  },
  {
    id: 'REP-02',
    nameEn: 'Weekly Food Cost & Waste Variance Audit (COGS)',
    nameAr: 'تقرير تدقيق تكلفة الأغذية والهدر الأسبوعي',
    frequency: 'WEEKLY',
    recipients: ['operations@enterprise-pos.com', 'kitchen@enterprise-pos.com'],
    format: 'EXCEL',
    lastRun: '2026-08-24 08:00:00',
    nextRun: '2026-08-31 08:00:00',
    status: 'ACTIVE',
  },
  {
    id: 'REP-03',
    nameEn: 'Monthly Regional Franchise Royalty & Tax Pack',
    nameAr: 'حزمة رسوم الامتياز الشهرية والإقرار الضريبي للفروع',
    frequency: 'MONTHLY',
    recipients: ['franchise-hq@enterprise-pos.com', 'tax@enterprise-pos.com'],
    format: 'PDF',
    lastRun: '2026-08-01 00:00:00',
    nextRun: '2026-09-01 00:00:00',
    status: 'ACTIVE',
  },
];
