import { Customer360Profile, MarketingCampaignJourney, DigitalGiftCard, SubscriptionMealPlan } from './types';

export const ENTERPRISE_CUSTOMERS_360: Customer360Profile[] = [
  {
    id: 'CUST-8091',
    name: 'Abdulaziz Al-Saud',
    phone: '+966 50 123 4567',
    email: 'abdulaziz@saudicorp.com',
    tier: 'VIP_BLACK',
    rfmSegment: 'CHAMPIONS',
    walletBalanceSar: 1250.0,
    loyaltyPoints: 4850,
    lifetimeSpendSar: 34890.0,
    totalOrdersCount: 142,
    averageOrderValueSar: 245.7,
    preferredChannel: 'Dine-In & VIP Catering',
    favoriteItems: ['Wagyu Truffle Burger', 'Single Origin V60', 'Lotus Brioche French Toast'],
    lastOrderDate: '2026-08-27 13:30',
    registeredDate: '2023-01-15',
    dietaryPreferences: ['Gluten-Friendly', 'No Dairy'],
    referralCode: 'AZIZ_VIP',
    successfulReferrals: 18,
  },
  {
    id: 'CUST-4120',
    name: 'Nouf Al-Dosari',
    phone: '+966 55 987 6543',
    email: 'nouf.dosari@techksa.io',
    tier: 'GOLD',
    rfmSegment: 'LOYAL_CUSTOMERS',
    walletBalanceSar: 340.0,
    loyaltyPoints: 1820,
    lifetimeSpendSar: 12450.0,
    totalOrdersCount: 68,
    averageOrderValueSar: 183.0,
    preferredChannel: 'Drive-Thru & App Pickup',
    favoriteItems: ['Crispy Nashville Chicken', 'Passion Fruit Mojito', 'Cheesy Loaded Fries'],
    lastOrderDate: '2026-08-26 19:45',
    registeredDate: '2024-04-10',
    dietaryPreferences: ['Halal Premium'],
    referralCode: 'NOUF_FOODIE',
    successfulReferrals: 7,
  },
  {
    id: 'CUST-2194',
    name: 'Fahad Al-Shehri',
    phone: '+966 54 321 0987',
    email: 'fahad.shehri@outlook.com',
    tier: 'SILVER',
    rfmSegment: 'AT_RISK',
    walletBalanceSar: 45.0,
    loyaltyPoints: 420,
    lifetimeSpendSar: 3890.0,
    totalOrdersCount: 22,
    averageOrderValueSar: 176.8,
    preferredChannel: 'Delivery Fleet',
    favoriteItems: ['Double Angus Cheeseburger', 'Salted Caramel Milkshake'],
    lastOrderDate: '2026-07-15 21:10',
    registeredDate: '2024-11-20',
    dietaryPreferences: ['None'],
    referralCode: 'FAHAD_REWARDS',
    successfulReferrals: 2,
  },
];

export const MARKETING_CAMPAIGN_JOURNEYS: MarketingCampaignJourney[] = [
  {
    id: 'CMP-01',
    nameEn: 'Automated WhatsApp VIP Dinner Invitation & Private Table Hold',
    nameAr: 'دعوة كبار العملاء التلقائية عبر الواتساب لحجز الطاولات الخاصة',
    channel: 'WHATSAPP',
    triggerEvent: 'POST_DINE_IN',
    audienceSegment: 'VIP & Champions (Spend > 5,000 SAR)',
    messageTemplateEn: 'Hello {{name}}, your chef reserve table is waiting at {{branch}}. Enjoy a complimentary artisanal dessert on us!',
    messageTemplateAr: 'أهلاً بك {{name}}، طاولتك الخاصة بانتظارك في {{branch}}. استمتع بحلوى الشيف المجانية مع زيارتك القادمة!',
    sentCount: 1420,
    openRatePercent: 98.4,
    conversionRatePercent: 32.6,
    revenueGeneratedSar: 184500,
    status: 'ACTIVE',
  },
  {
    id: 'CMP-02',
    nameEn: 'At-Risk Win-Back WhatsApp Journey (30-Day Inactive)',
    nameAr: 'حملة استعادة العملاء غير النشطين عبر الواتساب (30 يوماً)',
    channel: 'WHATSAPP',
    triggerEvent: 'INACTIVE_30_DAYS',
    audienceSegment: 'At-Risk & Lapsed Regulars',
    messageTemplateEn: 'We miss you {{name}}! We deposited 50 SAR in your OmniWallet. Redeem it on your next craving today!',
    messageTemplateAr: 'اشتقنا لك {{name}}! أودعنا 50 ريالاً في محفظتك الإلكترونية، استخدمها اليوم لتناول وجبتك المفضلة!',
    sentCount: 3840,
    openRatePercent: 94.1,
    conversionRatePercent: 24.8,
    revenueGeneratedSar: 142000,
    status: 'ACTIVE',
  },
  {
    id: 'CMP-03',
    nameEn: 'Daily Lunch Rush Push Notification with Dynamic Countdown',
    nameAr: 'إشعار فوري لغداء العمل مع عد تنازلي للخصم',
    channel: 'PUSH_NOTIFICATION',
    triggerEvent: 'LUNCH_RUSH',
    audienceSegment: 'Office & Business District Workers',
    messageTemplateEn: 'Lunch break sorted! 20% off express meal combos for the next 45 minutes.',
    messageTemplateAr: 'وجبة غدائك جاهزة! خصم 20% على وجبات التوفير السريعة خلال الـ 45 دقيقة القادمة.',
    sentCount: 28400,
    openRatePercent: 42.1,
    conversionRatePercent: 14.5,
    revenueGeneratedSar: 298000,
    status: 'ACTIVE',
  },
];

export const ACTIVE_GIFT_CARDS: DigitalGiftCard[] = [
  {
    code: 'GIFT-OMNI-98204-SAR',
    pin: '8492',
    recipientName: 'Mona Al-Khatib',
    recipientPhone: '+966 50 491 8293',
    initialBalanceSar: 500.0,
    currentBalanceSar: 350.0,
    expiryDate: '2027-08-27',
    status: 'ACTIVE',
  },
  {
    code: 'GIFT-OMNI-10492-SAR',
    pin: '1093',
    recipientName: 'Khaled Bin Sultan',
    recipientPhone: '+966 55 102 9384',
    initialBalanceSar: 1000.0,
    currentBalanceSar: 1000.0,
    expiryDate: '2027-12-31',
    status: 'ACTIVE',
  },
];

export const SUBSCRIPTION_MEAL_PLANS: SubscriptionMealPlan[] = [
  {
    id: 'SUB-FIT-20',
    planNameEn: 'Executive High-Protein Clean Box (20 Meals/Mo)',
    planNameAr: 'صندوق البروتين الصحي التنفيذي (20 وجبة شهرياً)',
    cadence: 'MONTHLY',
    mealsPerWeek: 5,
    pricePerPeriodSar: 1450.0,
    activeSubscribers: 420,
    mrrSar: 609000,
    retentionRatePercent: 91.4,
  },
  {
    id: 'SUB-COFFEE-DAILY',
    planNameEn: 'Daily Specialty Specialty Coffee Pass (30 Drinks)',
    planNameAr: 'اشتراك القهوة المختصة اليومي (30 مشروب شهرياً)',
    cadence: 'MONTHLY',
    mealsPerWeek: 7,
    pricePerPeriodSar: 350.0,
    activeSubscribers: 1850,
    mrrSar: 647500,
    retentionRatePercent: 94.8,
  },
];
